# YAML file with all configuration
paths:   # Note: All paths should have a "/" at the end!
    raw_data: /project/meteo/scratch/S.Rasp/convective_variability_data/raw_data/
    preproc_data: /project/meteo/scratch/S.Rasp/convective_variability_data/preproc_data/
    radar_data: /project/meteo/w2w/A6/radolan/netcdf_cosmo_de/
    radar_prefx: raa01-rw_10000-
    radar_sufix: -dwd---bin.nc
    figures: /home/s/S.Rasp/repositories/convective_variability_analysis/figures/

domain:
    ie: 357   # Model run grid points in x
    je: 357   # Model run grid points in j
    ana_irange: 256   # Range of analysis domain in x
    ana_jrange: 256   # Range of analysis domain in y
    radar_istart: 112   # Start of radar domain in x
    radar_istop: -93   # End of radar domain in x
    radar_jstart: 72   # Start of radar domain in y
    radar_jstop: -93   # End of radar domain in y
    dx: 2.8e3  # Grid spacing in x-y

colors:
    det: '#009500'
    obs: black
    ens: '#008FD4'
    ens_range: "#4AF2FF"
    third: '#E95E83'

plotting:
    date_fmt: '%d %b'
    page_width: 7.87
