# YAML file with all configuration
paths:   # Note: All paths should have a "/" at the end!
    raw_data: /project/meteo/scratch/users/stephan.rasp/convective_variability_data/raw_data/
    preproc_data: /project/meteo/scratch/users/stephan.rasp/convective_variability_data/preproc_data/
    radar_data: /project/meteo/w2w/A6/radolan/netcdf_cosmo_de/